/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqturistico.vistas;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import paqturistico.control.DestinoData;
import paqturistico.control.TransporteData;
import paqturistico.modelo.Conexion;
import paqturistico.modelo.Destino;
import paqturistico.modelo.Transporte;

/**
 *
 * @author Usuario
 */
public class VistaAgregarTransporte extends javax.swing.JInternalFrame {
    private Conexion con;
    private DestinoData dd;
    private TransporteData td;
    /**
     * Creates new form VistaAgregarTransporte
     */
    public VistaAgregarTransporte() {
        initComponents();        
        try {
            con = new Conexion();
            dd = new DestinoData(con);
            td = new TransporteData(con);
            llenarDestinos();
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar la vista carga de Menú\n"+ex);
        }
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbActivo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jtTipo = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jcomboDestino = new javax.swing.JComboBox<>();
        jcbActivo = new javax.swing.JCheckBox();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Transporte");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Destino:");

        jLabel5.setText("Activo:");

        jbActivo.setText("Limpiar");
        jbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActivoActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jcomboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Destino.." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jbActivo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcomboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbActivo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGuardar)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcomboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jcbActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActivo)
                    .addComponent(jbGuardar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActivoActionPerformed
        // TODO add your handling code here:
        jcbActivo.setSelected(false);
        jtTipo.setText("");
        jtPrecio.setText("");        
        jcomboDestino.setSelectedIndex(0);
    }//GEN-LAST:event_jbActivoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        Transporte t = new Transporte();
        Destino d;
        if(jcomboDestino.getSelectedIndex() == 0 || jtTipo.getText().isEmpty() || jtPrecio.getText().isEmpty() || !jtPrecio.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            if(!jtPrecio.getText().matches("[+-]?\\d*(\\.\\d+)?")){
                JOptionPane.showMessageDialog(this, "Debe ingresar un valor numérico para el precio.");
            }
            JOptionPane.showMessageDialog(this, "No ha seleccionado todos los datos necesarios");
        }else{                
            d = dd.obtenerDestino(jcomboDestino.getSelectedItem().toString());
            
            t.setTipo(jtTipo.getText());
            t.setIdDestino(d);
            t.setActivo(jcbActivo.isSelected());
            t.setPrecio(Integer.parseInt(jtPrecio.getText()));            
            

            td.guardarTransporte(t);
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

     private void llenarDestinos(){
        List<Destino> destinos = dd.obtenerDestinosActivos();
        
        for(Destino d: destinos){
            jcomboDestino.addItem(d.getNombre());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbActivo;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JComboBox<String> jcomboDestino;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables
}
