/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqturistico.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import paqturistico.control.AlojamientoData;
import paqturistico.control.MenuData;
import paqturistico.modelo.Alojamiento;
import paqturistico.modelo.Conexion;
import paqturistico.modelo.Menu;

/**
 *
 * @author Usuario
 */
public class VistaAgregarMenu extends javax.swing.JInternalFrame {
    private Conexion con;
    private MenuData md;
    private AlojamientoData ad;
    /**
     * Creates new form VistaAgregarMenu
     */
    public VistaAgregarMenu() {
        initComponents();
        try{
            con = new Conexion();
            md = new MenuData(con);
            ad = new AlojamientoData(con);           
            llenarAloj();
        }catch(ClassNotFoundException err){
            System.out.println("Error al cargar la vista carga de Menú\n"+err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcomboAlojamiento = new javax.swing.JComboBox<>();
        jtPrecio = new javax.swing.JTextField();
        jcbActivo = new javax.swing.JCheckBox();
        jbLimpiar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jcTipo = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Menú");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Alojamiento:");

        jLabel5.setText("Activo");

        jcomboAlojamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un alojamiento..." }));

        jtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPrecioFocusLost(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un menu", "Sin pension", "Solo desayuno", "Media pension", "Pension completa" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcomboAlojamiento, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbActivo)
                                    .addComponent(jcTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbGuardar)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcomboAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcbActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar)
                    .addComponent(jbGuardar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jcbActivo.setSelected(false);
        jcTipo.setSelectedIndex(0);
        jtPrecio.setText("");        
        jcomboAlojamiento.setSelectedIndex(0);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:        
        Menu menu = new Menu();
        List<Menu> menus = new ArrayList<>();
        
        if(jcomboAlojamiento.getSelectedIndex() == 0 || jcTipo.getSelectedIndex()==0 || jtPrecio.getText().isEmpty() || !jtPrecio.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            if(!jtPrecio.getText().matches("[+-]?\\d*(\\.\\d+)?")){
                JOptionPane.showMessageDialog(this, "Debe ingresar un valor numérico para el precio.");
            }
            JOptionPane.showMessageDialog(this, "No ha seleccionado todos los datos necesarios");
        }else{    
            Alojamiento alojamiento = ad.obtenerAlojamiento(jcomboAlojamiento.getSelectedItem().toString());
           
            menu.setIdAlojamiento(alojamiento);
            menu.setActivo(jcbActivo.isSelected());
            menu.setPrecio(Integer.parseInt(jtPrecio.getText()));
            menu.setTipo(jcTipo.getSelectedItem().toString());
          
         
             menus= md.obtenerMenuPorAlojamiento(alojamiento.getNombre());
             
              if(menus.contains(menu)){
            
                 JOptionPane.showMessageDialog(this, "El alojamiento ya cuenta con ese menu");
            }else{
             md.guardarMenu(menu);
        }}
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrecioFocusLost
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(jtPrecio.getText());
            
        }catch(NumberFormatException nf) {
             JOptionPane.showMessageDialog(this, "No es un numero válido");
             jtPrecio.requestFocus();
        }
    }//GEN-LAST:event_jtPrecioFocusLost
    private void llenarAloj(){
        List<Alojamiento> alojamientos = ad.obtenerAlojamientosActivos();
        
        for(Alojamiento a: alojamientos){
            jcomboAlojamiento.addItem(a.getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JComboBox<String> jcomboAlojamiento;
    private javax.swing.JTextField jtPrecio;
    // End of variables declaration//GEN-END:variables
}
