/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqturistico.vistas;

import java.util.List;
import javax.swing.JOptionPane;
import paqturistico.control.DestinoData;
import paqturistico.modelo.Conexion;
import paqturistico.modelo.Destino;

/**
 *
 * @author familia
 */
public class VistaActualizarDestino extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarDestino
     */
    
    private DestinoData dd;
    private Conexion con;
    
    public VistaActualizarDestino() {
        initComponents();
        
        try{
            con = new Conexion();
            dd = new DestinoData(con);
            
            llenarDestinos();
            
        }catch(ClassNotFoundException error){
            System.out.println("Error al iniciar la vista Actualizar Destino\n"+error);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbNombre = new javax.swing.JComboBox<>();
        jtPais = new javax.swing.JTextField();
        jtId = new javax.swing.JTextField();
        jcActivo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jcbNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--" }));
        jcbNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNombreItemStateChanged(evt);
            }
        });

        jtId.setEditable(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Pais:");

        jLabel3.setText("ID:");

        jLabel4.setText("Activo:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Actualizar Destino");

        jLabel6.setText("Nombre:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtNombre)
                                .addComponent(jcActivo)
                                .addComponent(jcbNombre, 0, 175, Short.MAX_VALUE)
                                .addComponent(jtPais)
                                .addComponent(jtId)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jcActivo))
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnLimpiar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        if (jcbNombre.getSelectedIndex() == 0) {
            
            JOptionPane.showMessageDialog(this, "Debe seleccionar algún destino.");
            
        } else if(jtNombre.getText().isEmpty() || jtPais.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "No ha completado todos los campos.");
            
        } else {
       
            Destino destino = new Destino();

            destino.setIdDestino(Integer.parseInt(jtId.getText()));
            destino.setNombre(jtNombre.getText());
            destino.setPais(jtPais.getText());
            destino.setActivo(jcActivo.isSelected());

            dd.actualizarDestino(destino);

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jcbNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNombreItemStateChanged
        // TODO add your handling code here:
        if (jcbNombre.getSelectedIndex() == 0) {
            jtId.setText("");
            jtNombre.setText("");
            jtPais.setText("");
        } else {
            Destino destino = dd.obtenerDestino(jcbNombre.getSelectedItem().toString());
            jtNombre.setText(destino.getNombre());
            jtId.setText("" + destino.getIdDestino());
            jtPais.setText(destino.getPais());
            jcActivo.setSelected(destino.isActivo());
        }
    }//GEN-LAST:event_jcbNombreItemStateChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jcbNombre.setSelectedIndex(0);
        jtId.setText("");
        jtNombre.setText("");
        jtPais.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void llenarDestinos(){
        
        List<Destino> destinos = dd.obtenerDestinos();
        Destino destino;
        
        if(!destinos.isEmpty()){
            for(Destino d: destinos){
                jcbNombre.addItem(d.getNombre());
            }
            
            destino = dd.obtenerDestino(jcbNombre.getSelectedItem().toString());
            jtNombre.setText(destino.getNombre());
            jtId.setText(""+destino.getIdDestino());
            jtPais.setText(destino.getPais());
            jcActivo.setSelected(destino.isActivo());
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox jcActivo;
    private javax.swing.JComboBox<String> jcbNombre;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPais;
    // End of variables declaration//GEN-END:variables
}
